RULE_PACK_VERSION = "2026.08.14"


SOURCES = {
    "k8s_nodes": "https://kubernetes.io/docs/reference/node/node-status/",
    "k8s_probes": "https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/",
    "k8s_debug_pods": "https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/",
    "k8s_pressure": "https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/",
    "k8s_logging": "https://kubernetes.io/docs/concepts/cluster-administration/logging/",
    "k8s_runtime": "https://kubernetes.io/docs/setup/production-environment/container-runtimes/",
    "k8s_124": "https://kubernetes.io/releases/1.24/",
    "k8s_131": "https://kubernetes.io/releases/1.31/",
    "deckhouse_containerd": "https://github.com/deckhouse/deckhouse/blob/main/CHANGELOG/CHANGELOG-v1.52.md",
    "kernel_cgroup2": "https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html",
    "kernel_psi": "https://www.kernel.org/doc/html/latest/accounting/psi.html",
    "systemd_journal": "https://www.freedesktop.org/software/systemd/man/journalctl.html",
    "cilium_troubleshooting": "https://docs.cilium.io/en/stable/operations/troubleshooting/",
    "kubeadm_certs": "https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-certs/",
    "kesl_compatibility": "https://support.kaspersky.com/KES4Linux/12.1.0/en-US/KES4Linux-12.1.0-en-US.pdf",
    "npd_kernel_v0825": "https://raw.githubusercontent.com/kubernetes/node-problem-detector/v0.8.25/config/kernel-monitor.json",
    "k8s_services": "https://kubernetes.io/docs/tasks/debug/debug-application/debug-service/",
    "k8s_dns": "https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/",
    "k8s_api_health": "https://kubernetes.io/docs/reference/using-api/health-checks/",
    "k8s_auth_config": "https://kubernetes.io/docs/reference/access-authn-authz/authentication-config/",
    "k8s_apiservice": "https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/",
    "k8s_leases": "https://kubernetes.io/docs/concepts/architecture/leases/",
    "k8s_storage": "https://kubernetes.io/docs/concepts/storage/",
    "k8s_volume_health": "https://kubernetes.io/docs/concepts/storage/volume-health-monitoring/",
    "k8s_network_policy": "https://kubernetes.io/docs/concepts/services-networking/network-policies/",
    "etcd_status": "https://etcd.io/docs/v3.5/tutorials/how-to-check-cluster-status/",
    "etcd_maintenance": "https://etcd.io/docs/v3.5/op-guide/maintenance/",
    "k8s_pdb": "https://kubernetes.io/docs/tasks/run-application/configure-pdb/",
    "k8s_version_skew": "https://kubernetes.io/releases/version-skew-policy/",
    "k8s_crictl": "https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/",
    "prometheus_api": "https://prometheus.io/docs/prometheus/latest/querying/api/",
    "coredns_troubleshooting": "https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/",
    "kubeadm_troubleshooting": "https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/",
}


def _entry(title, classification, sources, description):
    return {
        "title": title,
        "classification": classification,
        "version_scope": "Kubernetes 1.24-1.31; Linux 5.x/6.x; component-specific checks require detected evidence",
        "sources": [SOURCES[name] for name in sources],
        "description": description,
    }


RULE_CATALOG = {
    "collector.node_gap": _entry("Неполный node snapshot", "fact", ("systemd_journal",), "Один или несколько узлов не были собраны."),
    "collector.evidence_gap": _entry("Часть обязательных данных собрана не полностью", "fact", ("systemd_journal", "k8s_logging"), "Один или несколько обязательных журналов или источников Kubernetes завершились ошибкой, превысили лимит времени либо были усечены по размеру."),
    "collector.normalization_truncated": _entry("Нормализация усечена", "fact", ("k8s_logging",), "Лимит нормализации отбросил часть категоризированных событий; зависимые правила имеют evidence gap."),
    "collector.boot_changed": _entry("Перезагрузка во время сбора", "fact", ("systemd_journal",), "Boot ID изменился между началом и концом node snapshot."),
    "inventory.mixed_kernel": _entry("Разные ядра", "fact", ("k8s_124", "k8s_131"), "Инвентаризационный drift, сам по себе не являющийся неисправностью."),
    "inventory.node_set_mismatch": _entry("Inventory и Node objects расходятся", "fact", ("k8s_nodes",), "Набор собранных node snapshots не совпадает с Kubernetes Node objects."),
    "inventory.mixed_apiserver_versions": _entry("Разные версии API server", "fact", ("k8s_version_skew",), "API server instances имеют разные minor versions; допустимость зависит от этапа upgrade и version-skew policy."),
    "node.low_root_disk": _entry("Мало места на корневой ФС", "fact", ("k8s_pressure",), "Свободно менее десяти процентов блоков корневой файловой системы."),
    "node.low_inodes": _entry("Мало inode", "fact", ("k8s_pressure",), "По df -Pi свободно менее пяти процентов inode."),
    "node.kubelet_inactive": _entry("kubelet не активен", "fact", ("k8s_nodes", "systemd_journal"), "systemd сообщает неактивное состояние kubelet."),
    "node.runtime_inactive": _entry("Container runtime не активен", "fact", ("k8s_runtime", "systemd_journal", "deckhouse_containerd"), "Все загруженные containerd, containerd-deckhouse или CRI-O units находятся вне active/activating."),
    "node.oom_detected": _entry("Обнаружен OOM kill", "fact", ("kernel_psi", "k8s_pressure"), "Kernel journal или container state содержит OOM evidence."),
    "node.conntrack_full": _entry("Переполнена conntrack table", "fact", ("cilium_troubleshooting",), "Kernel journal содержит сообщение table full."),
    "node.kernel_oops": _entry("Kernel oops", "fact", ("npd_kernel_v0825",), "Kernel journal совпал с адаптированной сигнатурой NPD KernelOops."),
    "node.task_hung": _entry("Зависшая kernel task", "fact", ("npd_kernel_v0825",), "Kernel сообщает, что task заблокирована дольше порога ядра."),
    "node.filesystem_error": _entry("Ошибка файловой системы", "fact", ("npd_kernel_v0825",), "Обнаружен EXT4 error или XFS shutdown."),
    "node.filesystem_warning": _entry("Предупреждение EXT4", "fact", ("npd_kernel_v0825",), "Kernel journal содержит EXT4 warning."),
    "node.io_error": _entry("Buffer I/O error", "fact", ("npd_kernel_v0825",), "Kernel journal содержит Buffer I/O error."),
    "node.hardware_error": _entry("Аппаратная ошибка", "fact", ("npd_kernel_v0825",), "Обнаружено CPER hardware event или memory read error."),
    "node.unregister_netdevice": _entry("Зависшее удаление netdevice", "fact", ("npd_kernel_v0825",), "Kernel ожидает освобождения сетевого устройства."),
    "kubernetes.node_not_ready": _entry("Node не Ready", "fact", ("k8s_nodes",), "Node condition Ready имеет False или Unknown."),
    "kubernetes.node_pressure": _entry("Node pressure", "fact", ("k8s_nodes", "k8s_pressure"), "MemoryPressure, DiskPressure или PIDPressure имеет True."),
    "kubernetes.network_unavailable": _entry("Сеть Node недоступна", "fact", ("k8s_nodes", "cilium_troubleshooting"), "NetworkUnavailable имеет True."),
    "kubernetes.pod_crash_loop": _entry("CrashLoopBackOff", "fact", ("k8s_debug_pods",), "Container state сообщает CrashLoopBackOff."),
    "kubernetes.image_pull_failure": _entry("Ошибка получения image", "fact", ("k8s_debug_pods",), "Container state или Event сообщает ErrImagePull/ImagePullBackOff."),
    "kubernetes.pod_oom_killed": _entry("Container завершён OOMKilled", "fact", ("k8s_pressure",), "Container lastState/state содержит OOMKilled."),
    "kubernetes.failed_scheduling": _entry("Pod не может быть запланирован", "fact", ("k8s_debug_pods",), "Event FailedScheduling или устойчивый эквивалент."),
    "kubernetes.workload_degraded": _entry("Workload не достиг desired state", "fact", ("k8s_debug_pods",), "Ready/available replicas меньше desired replicas."),
    "kubernetes.service_no_endpoints": _entry("Service без EndpointSlice", "fact", ("k8s_services",), "Selector-based Service не имеет ни одного EndpointSlice."),
    "kubernetes.service_no_ready_endpoints": _entry("Service без ready endpoints", "fact", ("k8s_services",), "EndpointSlice существуют, но ни один endpoint не готов обслуживать трафик."),
    "kubernetes.service_port_unresolved": _entry("Service port не разрешён", "hypothesis", ("k8s_services",), "EndpointSlice не содержит ожидаемый backend port для selector-based Service."),
    "dns.kube_dns_unavailable": _entry("Cluster DNS недоступен", "fact", ("k8s_dns",), "kube-dns Service, ready endpoints или CoreDNS Pods отсутствуют/нездоровы."),
    "dns.cluster_dns_mismatch": _entry("kubelet clusterDNS не совпадает с Service", "fact", ("k8s_dns",), "Явный clusterDNS kubelet отличается от ClusterIP kube-dns Service."),
    "controlplane.api_readyz_failed": _entry("API server readyz failed", "fact", ("k8s_api_health",), "Raw /readyz или одна из его проверок завершилась ошибкой."),
    "controlplane.authentication_config_read_error": _entry("API server повторно не прочитал authentication config", "fact", ("k8s_auth_config",), "Повторные записи выводятся только когда текущее наличие и читаемость host-файла, успешный readyz и готовность всех собранных kube-apiserver Pod одновременно не подтверждены. Разрешившаяся гонка Deckhouse reconciliation скрывается."),
    "controlplane.apiservice_unavailable": _entry("Aggregated APIService недоступен", "fact", ("k8s_apiservice",), "APIService condition Available имеет False или Unknown."),
    "controlplane.node_lease_stale": _entry("Node Lease отсутствует или отстаёт", "correlation", ("k8s_leases", "k8s_nodes"), "Node Lease отсутствует либо существенно отстаёт от свежей peer Lease."),
    "controlplane.static_pod_unhealthy": _entry("Control-plane static Pod нездоров", "fact", ("k8s_api_health", "k8s_debug_pods"), "etcd/apiserver/scheduler/controller-manager Pod не Running или container не Ready."),
    "collector.etcd_evidence_gap": _entry("etcd evidence недоступен", "fact", ("etcd_status",), "На control-plane узле не удалось выполнить полный набор read-only etcd checks."),
    "etcd.unhealthy": _entry("etcd endpoint unhealthy", "fact", ("etcd_status",), "etcdctl endpoint health явно вернул health=false или error."),
    "etcd.alarm_active": _entry("etcd alarm активен", "fact", ("etcd_maintenance",), "etcdctl alarm list вернул один или несколько alarms."),
    "etcd.topology_inconsistent": _entry("etcd topology inconsistent", "fact", ("etcd_status",), "Endpoint status сообщает отсутствие/разные leader или разные cluster ID."),
    "storage.pvc_pending": _entry("PVC находится в Pending", "fact", ("k8s_storage",), "PersistentVolumeClaim имеет phase Pending; причина отдельно не предполагается."),
    "storage.storage_class_missing": _entry("StorageClass отсутствует", "fact", ("k8s_storage",), "PVC с явным storageClassName ссылается на отсутствующий StorageClass."),
    "storage.pv_failed": _entry("PersistentVolume Failed", "fact", ("k8s_storage",), "PersistentVolume имеет phase Failed."),
    "storage.volume_attachment_failed": _entry("VolumeAttachment failed", "fact", ("k8s_storage", "k8s_volume_health"), "VolumeAttachment attached=false и содержит attach/detach error."),
    "storage.csi_driver_registration_gap": _entry("CSI driver registration gap", "hypothesis", ("k8s_storage",), "CSI driver из PV/VolumeAttachment не найден в CSIDriver или CSINode evidence."),
    "cilium.endpoint_unhealthy": _entry("CiliumEndpoint нездоров", "fact", ("cilium_troubleshooting",), "CiliumEndpoint state/health явно не ready/ok."),
    "cilium.node_ipam_error": _entry("CiliumNode IPAM error", "fact", ("cilium_troubleshooting",), "CiliumNode status.ipam.operator-status содержит error."),
    "cilium.policy_import_failed": _entry("Cilium policy import failed", "fact", ("cilium_troubleshooting", "k8s_network_policy"), "Cilium policy status содержит ok=false или error."),
    "kubernetes.probe_failures": _entry("Ошибки health probes", "fact", ("k8s_probes",), "Events или logs содержат readiness/liveness/startup probe failures."),
    "network.ipv6_disabled": _entry("IPv6 отключён", "fact", ("cilium_troubleshooting",), "Effective disable_ipv6=1; причинность определяется только дополнительной корреляцией."),
    "network.cni_unavailable": _entry("CNI недоступен", "hypothesis", ("cilium_troubleshooting",), "CNI/network plugin evidence обнаружен в нескольких источниках."),
    "cilium.unhealthy": _entry("Компоненты Cilium нездоровы", "fact", ("cilium_troubleshooting",), "Cilium Pod/container state или status command сообщает неисправность."),
    "cgroup.controllers_missing": _entry("Нет cgroup v2 controllers", "hypothesis", ("kernel_cgroup2", "k8s_runtime"), "cpu/io отсутствуют; без ошибки kubelet/runtime это не считается причиной."),
    "cgroup.driver_mismatch": _entry("Разные cgroup drivers kubelet/runtime", "fact", ("k8s_runtime", "kernel_cgroup2"), "Явно обнаруженные cgroupDriver kubelet и runtime не совпадают."),
    "cgroup.service_failure": _entry("cgroup denial связан с отказом сервиса", "correlation", ("kernel_cgroup2", "k8s_runtime"), "cgroup access denial и отказ kubelet/runtime произошли на одном узле в одном окне."),
    "security_agent.cgroup_denial": _entry("KESL и cgroup denial", "correlation", ("kernel_cgroup2", "kesl_compatibility"), "KESL установлен и обнаружено cgroup denial; правило не утверждает, что KESL является причиной."),
    "security_agent.ptrace_alert": _entry("Kernel ptrace alert security agent", "fact", ("systemd_journal", "kesl_compatibility"), "Kernel/security agent зарегистрировал ptrace attack message; правило не утверждает вредоносность процесса или влияние на Kubernetes."),
    "time.not_synchronized": _entry("Время не синхронизировано", "fact", ("systemd_journal",), "timedatectl/chrony сообщает отсутствие синхронизации."),
    "certificate.expiring": _entry("Сертификат истёк или скоро истечёт", "fact", ("kubeadm_certs",), "notAfter находится в прошлом или ближе 30 суток."),
    "correlation.node_runtime_failure": _entry("Node NotReady и runtime/kubelet failure", "correlation", ("k8s_nodes", "k8s_runtime"), "События совпали на одном узле в 15-минутном окне."),
    "correlation.node_cni_failure": _entry("Node/Pod failure и CNI failure", "correlation", ("k8s_nodes", "cilium_troubleshooting"), "События совпали на одном узле в 15-минутном окне."),
    "correlation.memory_oom_failure": _entry("MemoryPressure и OOM", "correlation", ("k8s_pressure", "kernel_psi"), "Pressure и OOM evidence совпали на одном узле в 15-минутном окне."),
    "correlation.certificate_api_failure": _entry("TLS/certificate и API failure", "correlation", ("kubeadm_certs", "k8s_nodes"), "Certificate и API/time errors совпали на одном узле в 15-минутном окне."),
    "correlation.conntrack_network_failure": _entry("Conntrack и сетевые ошибки", "correlation", ("cilium_troubleshooting",), "Conntrack overflow и network/probe errors совпали на одном узле в 15-минутном окне."),
    "correlation.probe_network_failure": _entry("Probe и network/DNS failure", "correlation", ("k8s_probes", "k8s_dns"), "Probe failure и сетевой/DNS класс ошибки совпали в одном scope и временном окне."),
    "correlation.storage_failure": _entry("DiskPressure и filesystem failure", "correlation", ("k8s_pressure", "npd_kernel_v0825"), "DiskPressure и ENOSPC/read-only filesystem evidence совпали на одном узле."),
    "storage.volume_operation_failure": _entry("Volume mount/attach failure", "fact", ("k8s_storage",), "Event сообщает FailedMount, FailedAttachVolume или эквивалентную ошибку volume operation."),
    "kubernetes.pod_waiting": _entry("Container ожидает запуска", "fact", ("k8s_debug_pods",), "Container Waiting содержит диагностический reason, не покрытый отдельным image/crash-loop правилом."),
    "kubernetes.init_container_failed": _entry("Init container failed", "fact", ("k8s_debug_pods",), "Init container ожидает с ошибкой либо завершился ненулевым кодом."),
    "kubernetes.container_exit_nonzero": _entry("Container завершён с ошибкой", "fact", ("k8s_debug_pods",), "Container в Failed Pod завершён ненулевым кодом без OOMKilled/Completed."),
    "kubernetes.pod_evicted": _entry("Pod evicted", "fact", ("k8s_pressure",), "Pod phase/reason сообщает eviction."),
    "kubernetes.pod_restart_storm": _entry("Высокий cumulative restartCount", "fact", ("k8s_debug_pods",), "restartCount не менее пяти и последнее завершение произошло не более часа назад; частота из одного snapshot не выводится."),
    "kubernetes.deployment_rollout_failed": _entry("Deployment rollout failed", "fact", ("k8s_debug_pods",), "Deployment condition сообщает ProgressDeadlineExceeded или ReplicaFailure."),
    "kubernetes.daemonset_misscheduled": _entry("DaemonSet misscheduled", "fact", ("k8s_debug_pods",), "DaemonSet status.numberMisscheduled больше нуля."),
    "kubernetes.statefulset_rollout_stalled": _entry("StatefulSet rollout failed", "fact", ("k8s_debug_pods",), "StatefulSet имеет явную failed condition; одно различие currentRevision/updateRevision считается нормальным rollout evidence."),
    "kubernetes.job_failed": _entry("Job failed", "fact", ("k8s_debug_pods",), "Job condition Failed=True."),
    "pdb.insufficient_healthy": _entry("PDB insufficient healthy", "fact", ("k8s_pdb",), "currentHealthy меньше desiredHealthy при ненулевом expectedPods."),
    "pdb.disruption_blocked": _entry("PDB blocks disruptions", "fact", ("k8s_pdb",), "disruptionsAllowed равно нулю; это эксплуатационный факт, не самостоятельный отказ."),
    "runtime.cri_not_ready": _entry("CRI RuntimeReady=False", "fact", ("k8s_crictl",), "crictl info сообщает отрицательное RuntimeReady condition."),
    "runtime.cri_network_not_ready": _entry("CRI NetworkReady=False", "fact", ("k8s_crictl", "cilium_troubleshooting"), "crictl info сообщает отрицательное NetworkReady condition."),
    "node.swap_active": _entry("Swap active при failSwapOn", "fact", ("kubeadm_troubleshooting",), "В /proc/swaps есть активные устройства, а kubelet failSwapOn не отключён."),
    "node.low_runtime_disk": _entry("Runtime filesystem заполнена", "fact", ("k8s_pressure",), "Отдельная backing filesystem kubelet/runtime/logs заполнена не менее чем на 90 процентов; дочерние read-only snapshot mounts игнорируются."),
    "dns.nameserver_limit_exceeded": _entry("Слишком много nameserver", "fact", ("coredns_troubleshooting",), "Resolver, используемый kubelet, содержит более трёх nameserver."),
    "dns.coredns_errors": _entry("CoreDNS resolution errors", "fact", ("coredns_troubleshooting",), "CoreDNS logs содержат SERVFAIL, forwarding loop или upstream failure; summary включает извлечённые query name, type и частоту."),
    "dns.coredns_config_empty": _entry("CoreDNS Corefile missing", "fact", ("coredns_troubleshooting",), "ConfigMap coredns не содержит непустой Corefile."),
    "certificate.kubelet_rotation_broken": _entry("Kubelet certificate rotation path broken", "fact", ("kubeadm_troubleshooting",), "rotateCertificates=true, но kubelet-client-current.pem отсутствует, не является symlink либо имеет недоступный target."),
    "inventory.unsupported_version_skew": _entry("Unsupported Kubernetes version skew", "fact", ("k8s_version_skew",), "Версии kubelet/kube-apiserver выходят за поддерживаемые границы, включая двух-minor предел для kubelet младше 1.25."),
    "prometheus.alert_firing": _entry("Prometheus firing alerts", "fact", ("prometheus_api",), "Prometheus API вернул один или несколько firing alerts."),
    "prometheus.config_reload_failed": _entry("Prometheus config reload failed", "fact", ("prometheus_api",), "runtimeinfo сообщает reloadConfigSuccess=false."),
    "prometheus.corruption_detected": _entry("Prometheus corruption detected", "fact", ("prometheus_api",), "runtimeinfo corruptionCount больше нуля."),
    "cilium.kube_proxy_replacement_disabled": _entry("Cilium kube-proxy replacement disabled", "fact", ("cilium_troubleshooting",), "kube-proxy Pods отсутствуют, а Cilium ConfigMap явно отключает kube-proxy replacement."),
    "cilium.service_frontend_missing": _entry("Cilium service frontend missing", "hypothesis", ("cilium_troubleshooting", "k8s_services"), "Read-only Cilium service map не содержит ожидаемый ClusterIP frontend."),
    "etcd.raft_apply_lag": _entry("etcd Raft apply lag", "hypothesis", ("etcd_status", "etcd_maintenance"), "raftAppliedIndex или revision существенно отстаёт."),
    "etcd.database_near_quota": _entry("etcd database near quota", "fact", ("etcd_maintenance",), "dbSize достиг не менее 80 процентов configured backend quota."),
    "etcd.fragmentation_high": _entry("etcd fragmentation high", "hypothesis", ("etcd_maintenance",), "dbSize существенно больше dbSizeInUse при достаточно крупном backend."),
    "etcd.member_version_drift": _entry("etcd member version drift", "fact", ("etcd_status",), "Endpoint status сообщает разные версии members."),
}


def rule_metadata(rule_id):
    return RULE_CATALOG.get(
        rule_id,
        {
            "title": rule_id,
            "classification": "hypothesis",
            "version_scope": "unspecified",
            "sources": [],
            "description": "Встроенное правило без отдельной карточки.",
        },
    )
